export enum Role {
    CUSTOMER = "CUSTOMER",
    VENDOR = "VENDOR",
    ADMIN = "ADMIN",
    PROVIDER = "PROVIDER",
    DELIVER = "DELIVER",
    DELIVER_MANAGER = "DELIVER_MANAGER",
    MANAGER = "MANAGER",
    MANAGERCUSTOMER = "MANAGERCUSTOMER",
    MANAGERVENDOR = "MANAGERVENDOR",
    MANAGERSHIPPING = "MANAGERSHIPPING",
}
